api = "0.2"

[buildpack]
  id = "paketo-buildpacks/bundler"
  name = "Bundle Install Buildpack"
  version = "0.0.1"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
[[stacks]]
  id = "io.buildpacks.stacks.bionic"
